### ISSUE TITLE
background noise

### ISSUE THREAD

**Issue by lmann** [hypenotic/sugar-animation#33]
So I played around with the background noise and found that the animation is much more fluid without it. I know it's kinda a cool thing, but it makes the animation a bit more jerky, at least on my computer. 

Thoughts?

**Comment by subsumo** [comment]
I actually think it's necessary at this point... doesn't jerk things on mine!

**Comment by lmann** [comment]
hmm..much smoother without. why is it necessary?

**Comment by subsumo** [comment]
It looks awesome- ties it together with the movie and gives it a moving feel. Your call, but I think it's just what the animation needs

**Comment by lmann** [comment]
with noisy background
![screen shot 2015-04-21 at 2 27 52 pm](https://cloud.githubusercontent.com/assets/1795752/7259639/aa7a6844-e832-11e4-8d14-76f169dd1195.png)

without noisy background
![screen shot 2015-04-21 at 2 28 30 pm](https://cloud.githubusercontent.com/assets/1795752/7259647/bbc06e3c-e832-11e4-9eb8-1847d86d8331.png)

**Comment by subsumo** [comment]
Your call, dude

**Comment by lmann** [comment]
performance vs design

**Comment by subsumo** [comment]
barry says kill it - 20% faster

**Comment by lmann** [comment]
ok

**Comment by subsumo** [comment]
commit: 'kill the noise'

**Comment by lmann** [comment]
the bees thank you
