### ISSUE TITLE
oh oh, the liver is hidden

### ISSUE THREAD

**Issue by lmann** [hypenotic/sugar-animation#35]
Help, we cant locate the liver. This man has no liver....hmmm. Now that the images are smaller, maybe move it over to where it was before.
![screen shot 2015-04-21 at 1 14 56 pm](https://cloud.githubusercontent.com/assets/1795752/7258136/8f3de9fc-e828-11e4-8086-27261520bd72.png)

Thoughts

**Comment by subsumo** [comment]
suggested by barry
will move to top right

**Comment by lmann** [comment]
![screen shot 2015-04-21 at 2 34 52 pm](https://cloud.githubusercontent.com/assets/1795752/7259763/af8d0066-e833-11e4-8e1d-65789c3ad024.png)

**Comment by subsumo** [comment]
his liver is in his head, the doctor cant even see it what the hell
